header:
  version: 14

target:
  - secure-image-minimal
  - secure-update-bundle

distro: poky

defaults:
  repos:
    branch: walnascar

repos:
  bitbake:
    url: https://git.openembedded.org/bitbake
    path: layers/bitbake
    branch: "2.12"
    layers:
      bitbake: excluded

  openembedded-core:
    url: https://git.openembedded.org/openembedded-core
    path: layers/oe-core
    layers:
      meta:

  meta-yocto:
    url: https://git.yoctoproject.org/meta-yocto
    path: layers/meta-yocto
    layers:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: https://github.com/openembedded/meta-openembedded
    path: layers/meta-openembedded
    layers:
      meta-oe:
      meta-perl:

  meta-security:
    url: https://git.yoctoproject.org/meta-security
    path: layers/meta-security

  meta-secure-core:
    url: https://github.com/Wind-River/meta-secure-core.git
    path: layers/meta-secure-core
    layers:
      meta-secure-core-common:
      meta-signing-key:
      meta-efi-secure-boot:

  # Using fork of meta-arm until build issues in master are fixed
  meta-arm-contrib:
    url: https://github.com/JSydll/meta-arm-contrib
    branch: master-next
    path: layers/meta-arm
    layers:
      meta-arm:
      meta-arm-toolchain:

  meta-rauc:
    url: https://github.com/rauc/meta-rauc.git
    path: layers/meta-rauc

  meta-generic-boot:
    layers:
      meta-generic-boot:

local_conf_header:
  distro: |
    DISTRO_FEATURES:append = " rauc systemd overlayfs security "
    INIT_MANAGER = "systemd"

  versioning: |
    SOFTWARE_VERSION ??= "0.0"

  common-security:
    # For now, keys are created in the build directory - a productive setup would require
    # proper key provisioning and infrastructure.
    SBSIGN_KEYS_DIR = "${TOPDIR}/secrets"