targets:
  main:
    resources: &common-resources
      - NetworkService:
          address: ""
          port: 22
          username: root
      - UpdateBundles:
          latest: "@@LG_ARTIFACT_MOUNTPOINT@@/@@UPDATE_BUNDLE_ARTIFACT@@"

    drivers:
      - QEMUDriver:
          qemu_bin: qemu_aarch64
          machine: virt,secure=on
          cpu: cortex-a72
          memory: 4G
          nic: user,model=virtio-net-pci
          bios: flash_bin
          extra_args: >-
            -drive if=none,file=@@LG_ARTIFACT_MOUNTPOINT@@/@@SYSTEM_IMAGE_ARTIFACT@@,format=qcow2,id=MMC0 
            -device sdhci-pci,sd-spec-version=3 
            -device sd-card,drive=MMC0 
            -snapshot
            @@QB_SMP@@ 
      - ShellDriver: &shell-config
          login_prompt: "virt-aarch64 login: "
          username: "root"
          prompt: 'root@virt-aarch64+:[^ ]+ '
          login_timeout: 200
      - SSHDriver: {}
      - QEMUSetupStrategy: {}

tools:
  qemu_aarch64: /usr/bin/qemu-system-aarch64

images:
  flash_bin: "@@LG_ARTIFACT_MOUNTPOINT@@/@@FIRMWARE_ARTIFACT@@"

imports:
  - environment.qemu.setup_strategy
  - environment.update
