features:
- os-canbus

targets:
  main:
    resources: &common-resources
      - NetworkService:
          address: ""
          port: 22
          username: root
      - UpdateBundles:
          latest: "@@LG_ARTIFACT_MOUNTPOINT@@/latest.@@UPDATE_BUNDLE_ARTIFACT@@"
          lts: "@@LG_ARTIFACT_MOUNTPOINT@@/lts.@@UPDATE_BUNDLE_ARTIFACT@@"
          manufacturing: "@@LG_ARTIFACT_MOUNTPOINT@@/manufacturing.@@UPDATE_BUNDLE_ARTIFACT@@"

    drivers:
      - QEMUDriver:
          qemu_bin: qemu_aarch64
          machine: virt
          cpu: @@QB_CPU_VALUE@@
          memory: @@QB_MEM_VALUE@@
          nic: user,model=virtio-net-pci
          bios: fw_latest
          disk: rootfs_latest
          extra_args: " @@QB_SMP@@ @@QB_EXTRA_OPTS@@ -snapshot"
      - ShellDriver: &shell-config
          login_prompt: "@@MACHINE@@ login: "
          username: "root"
          prompt: 'root@@@MACHINE@@+:[^ ]+ '
          login_timeout: 200
      - SSHDriver: {}
      - QEMUSetupStrategy: {}

  lts:
    resources: *common-resources
    drivers:
      - QEMUDriver:
          qemu_bin: qemu_aarch64
          machine: virt
          cpu: @@QB_CPU_VALUE@@
          memory: @@QB_MEM_VALUE@@
          nic: user,model=virtio-net-pci
          bios: fw_lts
          disk: rootfs_lts
          extra_args: " @@QB_SMP@@ @@QB_EXTRA_OPTS@@ -snapshot"
      - ShellDriver: *shell-config
      - SSHDriver: {}
      - QEMUSetupStrategy: {}

  manufacturing:
    resources: *common-resources
    drivers:
      - QEMUDriver:
          qemu_bin: qemu_aarch64
          machine: virt
          cpu: @@QB_CPU_VALUE@@
          memory: @@QB_MEM_VALUE@@
          nic: user,model=virtio-net-pci
          bios: fw_manufacturing
          disk: rootfs_manufacturing
          extra_args: " @@QB_SMP@@ @@QB_EXTRA_OPTS@@ -snapshot"
      - ShellDriver: *shell-config
      - SSHDriver: {}
      - QEMUSetupStrategy: {}

tools:
  qemu_aarch64: /usr/bin/qemu-system-aarch64

images:
  fw_latest: "@@LG_ARTIFACT_MOUNTPOINT@@/latest.@@FIRMWARE_ARTIFACT@@"
  rootfs_latest: "@@LG_ARTIFACT_MOUNTPOINT@@/latest.@@SYSTEM_IMAGE_ARTIFACT@@"
  fw_lts: "@@LG_ARTIFACT_MOUNTPOINT@@/lts.@@FIRMWARE_ARTIFACT@@"
  rootfs_lts: "@@LG_ARTIFACT_MOUNTPOINT@@/lts.@@SYSTEM_IMAGE_ARTIFACT@@"
  fw_manufacturing: "@@LG_ARTIFACT_MOUNTPOINT@@/manufacturing.@@FIRMWARE_ARTIFACT@@"
  rootfs_manufacturing: "@@LG_ARTIFACT_MOUNTPOINT@@/manufacturing.@@SYSTEM_IMAGE_ARTIFACT@@"

imports:
  - environment.qemu.setup_strategy
  - environment.update
