targets:
  main:
    resources: &common-resources
      - NetworkService:
          address: ""
          port: 22
          username: root
      - UpdateBundles:
          latest: "@@LG_ARTIFACT_MOUNTPOINT@@/@@UPDATE_BUNDLE_ARTIFACT@@"

    drivers:
      - QEMUDriver:
          qemu_bin: qemu_aarch64
          machine: virt,secure=on
          cpu: cortex-a72
          memory: 4G
          nic: user,model=virtio-net-pci
          bios: flash_bin
          disk: rootfs
          extra_args: " @@QB_SMP@@ -drive id=disk1,file=@@LG_ARTIFACT_MOUNTPOINT@@/@@ESP_IMAGE_ARTIFACT@@,if=none,format=qcow2 -device virtio-blk-device,drive=disk1 -snapshot"
      - ShellDriver: &shell-config
          login_prompt: "virt-aarch64 login: "
          username: "root"
          prompt: 'root@virt-aarch64+:[^ ]+ '
          login_timeout: 200
      - SSHDriver: {}
      - QEMUSetupStrategy: {}

tools:
  qemu_aarch64: /usr/bin/qemu-system-aarch64

images:
  flash_bin: "@@LG_ARTIFACT_MOUNTPOINT@@/@@FIRMWARE_ARTIFACT@@"
  rootfs: "@@LG_ARTIFACT_MOUNTPOINT@@/@@SYSTEM_IMAGE_ARTIFACT@@"

imports:
  - environment.qemu.setup_strategy
  - environment.update
